// Generated by scripts/generate-engine.mjs. Do not edit.
pub const build_id = "ghostty:fe317f850c3ab212f6638122c459b9b48b99a016:wterm-build-sha256:400343404fe750828306ff76908630e2d445daebbf7147f3fac773b96ff9b2f3";
pub const terminal_name = "xterm-256color";
pub const xtversion = "wterm 0.3.4";
