// Generated by scripts/generate-engine.mjs. Do not edit.
pub const build_id = "ghostty:fe317f850c3ab212f6638122c459b9b48b99a016:wterm-build-sha256:671856f1dee71f390c042f8b7981759fb9f79281b04b762c25a57e4928a8a682";
pub const terminal_name = "xterm-256color";
pub const xtversion = "wterm 0.3.4";
