// Generated by scripts/generate-engine.mjs. Do not edit.
pub const build_id = "ghostty:fe317f850c3ab212f6638122c459b9b48b99a016:wterm-build-sha256:88bf0b0fa586733f84df70d11de24313d76a0e7c25af6d72582ddc36de68020b";
pub const terminal_name = "xterm-256color";
pub const xtversion = "wterm 0.3.4";
