// Generated by scripts/generate-engine.mjs. Do not edit.
export const GHOSTTY_ENGINE_PROVENANCE = Object.freeze({
  adapterAbiVersion: 4,
  adapterSourceSha256:
    "b042d47cfc4562ed322806711c48f57baae50181cb9a056e3205256c0d5e1e72",
  buildScriptSha256:
    "23ee2604eeb905cf25629105f65b7168c846118776fa62d3a73060106f178ca5",
  buildSourceSha256:
    "1b7f9ea163c4345c191d01a1d6f1fb0a0f873a39241cfa35b86ec94c362e9d95",
  committedWasmSha256:
    "6d817a66a606e88ec3c0cefa9ab26f042b285577095588b6569d62838718edc5",
  dependencyManifestSha256:
    "75261ca43a5c50dd88c5b55577cf1db28196e28f374ac6d52766264e8de26bf4",
  ghosttyCommit: "fe317f850c3ab212f6638122c459b9b48b99a016",
  ghosttyPackageHash:
    "ghostty-1.3.2-dev-5UdBCxyDUwWzvNOIPY-t4kzXgd0NAKxYPkpDkW_d0pwd",
  ghosttyRepository: "Eric-Song-Nop/ghostty",
  ghosttySourceSha256:
    "6f4fd9bba1ebffe291bf45eeb83bd04eaddb35d9fdaebd009cefd40d63a4ab07",
  ghosttyUpstreamBaseCommit: "f2d5758f6305867dc36b36293c6165d8152b853e",
  ghosttyVtFeatures: "default",
  manifestGeneratorSha256:
    "69c4f240cdad64a389353f3a93e4fdec6a4d4a7e9bfba8d49285b44b7c42f75f",
  optimize: "ReleaseSmall",
  patches: [
    {
      baseCommit: "f2d5758f6305867dc36b36293c6165d8152b853e",
      commit: "fe317f850c3ab212f6638122c459b9b48b99a016",
      id: "ansi-decrqm-dispatch",
      repository: "Eric-Song-Nop/ghostty",
    },
  ],
  patchsetSha256:
    "0bff825b43eb7e3e8850b0b1588822558c685449a5215201acccb7b0d12cd9e2",
  snapshotSchemaSha256:
    "de359f274c5492378c40c571d5b17a383d2863b829fe6e15e8d00ebc146f6be9",
  snapshotSchemaVersion: 1,
  target: "wasm32-freestanding",
  terminalProfile: {
    colorScheme: "derived-from-background",
    deviceAttributes: "VT220+ANSI-color",
    term: "xterm-256color",
    xtversion: "wterm 0.3.4",
  },
  unicodeWidthPolicy: "ghostty-default",
  zigVersion: "0.16.0",
} as const);

export const GHOSTTY_BUILD_ID =
  "ghostty:fe317f850c3ab212f6638122c459b9b48b99a016:wterm-build-sha256:88bf0b0fa586733f84df70d11de24313d76a0e7c25af6d72582ddc36de68020b";

export const GHOSTTY_ENGINE_ID =
  "ghostty:fe317f850c3ab212f6638122c459b9b48b99a016:wterm-engine-sha256:2836a71302115fb2989235666560fc4b6a5739158478e85e4d25bd1f1248fe96";

export const GHOSTTY_WASM_SHA256 =
  "6d817a66a606e88ec3c0cefa9ab26f042b285577095588b6569d62838718edc5";

export const GHOSTTY_TERMINAL_PROFILE =
  GHOSTTY_ENGINE_PROVENANCE.terminalProfile;

export const GHOSTTY_ENGINE_MANIFEST = Object.freeze({
  buildId: GHOSTTY_BUILD_ID,
  engineId: GHOSTTY_ENGINE_ID,
  provenance: GHOSTTY_ENGINE_PROVENANCE,
  wasmSha256: GHOSTTY_WASM_SHA256,
} as const);

export type GhosttyEngineManifest = typeof GHOSTTY_ENGINE_MANIFEST;
